CREATE SEQUENCE SEQ_ANSWER INCREMENT BY 1 START WITH 1 NOCYCLE CACHE 20 NOORDER;
CREATE SEQUENCE SEQ_ANSWER_TYPE INCREMENT BY 1 START WITH 1 NOCYCLE CACHE 20 NOORDER;
CREATE SEQUENCE SEQ_C_FILE INCREMENT BY 1 START WITH 1 NOCYCLE CACHE 20 NOORDER;
CREATE SEQUENCE SEQ_C_IMAGE INCREMENT BY 1 START WITH 1 NOCYCLE CACHE 20 NOORDER;
CREATE SEQUENCE SEQ_C_QUESTION_TYPE INCREMENT BY 1 START WITH 1 NOCYCLE CACHE 20 NOORDER;
CREATE SEQUENCE SEQ_QUESTION INCREMENT BY 1 START WITH 1 NOCYCLE CACHE 20 NOORDER;
CREATE SEQUENCE SEQ_R_ANSWER_IMAGE INCREMENT BY 1 START WITH 1 NOCYCLE CACHE 20 NOORDER;
CREATE SEQUENCE SEQ_R_QUESTION_IMAGE INCREMENT BY 1 START WITH 1 NOCYCLE CACHE 20 NOORDER;