ALTER TABLE C_IMAGE ADD  CONSTRAINT C_IMAGE_C_FILE_FK
 FOREIGN KEY (FILE_ID) 
  REFERENCES C_FILE (ID);
	
ALTER TABLE ANSWER ADD  CONSTRAINT ANSWER_C_ANSWER_TYPE_FK
 FOREIGN KEY (ANSWER_TYPE_ID) 
  REFERENCES C_ANSWER_TYPE (ID);
	
ALTER TABLE QUESTION ADD  CONSTRAINT QUESTION_C_QUESTION_TYPE_FK
 FOREIGN KEY (QUESTION_TYPE_ID) 
  REFERENCES C_QUESTION_TYPE (ID);
	
ALTER TABLE R_ANSWER_IMAGE ADD  CONSTRAINT R_ANSWER_IMAGE_ANSWER_FK
 FOREIGN KEY (ANSWER_ID) 
  REFERENCES ANSWER (ID);
	
ALTER TABLE R_ANSWER_IMAGE ADD  CONSTRAINT R_ANSWER_IMAGE_IMAGE_FK
 FOREIGN KEY (IMAGE_ID) 
  REFERENCES C_IMAGE (ID);
	
ALTER TABLE R_QUESTION_IMAGE ADD  CONSTRAINT R_QUESTION_IMAGE_QUESTION_FK
 FOREIGN KEY (QUESTION_ID) 
  REFERENCES QUESTION (ID);
	
ALTER TABLE R_QUESTION_IMAGE ADD  CONSTRAINT R_QUESTION_IMAGE_IMAGE_FK
 FOREIGN KEY (IMAGE_ID) 
  REFERENCES C_IMAGE (ID);