CREATE TABLE ANSWER ( 
  ID        NUMBER (10)
     CONSTRAINT ANSWER_ID_NN   NOT NULL, 
	ANSWER_TYPE_ID NUMBER(10)
		 CONSTRAINT ANSWER_ANSWER_TYPE_ID_NN NOT NULL,
  DESCRIPTION      CLOB
		 CONSTRAINT ANSWER_DESCRIPTION_NN   NOT NULL, 
  IS_CORRECT  CHAR (1)      DEFAULT 0
     CONSTRAINT ANSWER_IS_CORRECT_NN   NOT NULL, 
	IS_ACTIVE  CHAR (1)      DEFAULT 1
     CONSTRAINT ANSWER_IS_ACTIVE_NN   NOT NULL, 
  LAST_UPD  DATE,
  CONSTRAINT ANSWER_PK
  PRIMARY KEY ( ID ) ) ; 

COMMENT ON TABLE ANSWER IS 'Provides various answers';

COMMENT ON COLUMN ANSWER.ID IS 'Unique system number';
COMMENT ON COLUMN ANSWER.ANSWER_TYPE_ID IS 'ID of the answer type';
COMMENT ON COLUMN ANSWER.DESCRIPTION IS 'Description of the answer';
COMMENT ON COLUMN ANSWER.IS_ACTIVE IS 'Whether the record is visible or deleted';
COMMENT ON COLUMN ANSWER.LAST_UPD IS 'Date of last modification';


CREATE OR REPLACE TRIGGER ANSWER_BRIU_TRG BEFORE INSERT OR UPDATE ON ANSWER FOR EACH ROW
BEGIN
	:NEW.LAST_UPD := SYSDATE;
END;
/

