CREATE TABLE C_FILE ( 
  ID                 NUMBER (10)
     CONSTRAINT C_FILE_ID_NN   NOT NULL, 
  NAME               VARCHAR2 (256 CHAR)
     CONSTRAINT C_FILE_NAME_NN   NOT NULL, 
  CONTENT            BLOB
     CONSTRAINT C_FILE_CONTENT_NN   NOT NULL, 
  MIME_TYPE          VARCHAR2 (256 CHAR), 
  CONTENT_LENGTH     NUMBER (10), 
  ORIGINAL_FILENAME  VARCHAR2 (512 CHAR), 
  IS_ACTIVE           CHAR (1)      DEFAULT 1
		 CONSTRAINT C_FILE_IS_ACTIVE_NN NOT NULL, 
  LAST_UPD           DATE, 
  CONSTRAINT C_FILE_PK
  PRIMARY KEY ( ID ) ) ; 
	
COMMENT ON TABLE C_FILE IS 'Contains uploaded files';

COMMENT ON COLUMN C_FILE.ID IS 'Unique system number';
COMMENT ON COLUMN C_FILE.NAME IS 'Name of the file';
COMMENT ON COLUMN C_FILE.CONTENT IS 'File content';
COMMENT ON COLUMN C_FILE.CONTENT_LENGTH IS 'Content length';
COMMENT ON COLUMN C_FILE.MIME_TYPE IS 'Content mime type';
COMMENT ON COLUMN C_FILE.ORIGINAL_FILENAME IS 'The name of the file that was uploaded';
COMMENT ON COLUMN C_FILE.IS_ACTIVE IS 'Whether the record is visible or deleted';
COMMENT ON COLUMN C_FILE.LAST_UPD IS 'Date of last modification';



CREATE OR REPLACE TRIGGER C_FILE_BRIU_TRG BEFORE INSERT OR UPDATE ON C_FILE FOR EACH ROW
BEGIN
	:NEW.LAST_UPD := SYSDATE;
END;
/