CREATE TABLE C_IMAGE ( 
  ID                 NUMBER (10)
     CONSTRAINT C_IMAGE_ID_NN   NOT NULL, 
  NAME               VARCHAR2 (256 CHAR)
     CONSTRAINT C_IMAGE_NAME_NN   NOT NULL, 
  DESCRIPTION        VARCHAR2(512 CHAR)
     CONSTRAINT C_IMAGE_DESCRIPTION_NN   NOT NULL, 
  FILE_ID						 NUMBER(10)
		 CONSTRAINT C_IMAGE_FILE_ID_NN NOT NULL,
	WIDTH							 NUMBER(10),
	HEIGHT						 NUMBER(10),
	IS_ACTIVE           CHAR (1)      DEFAULT 1
		 CONSTRAINT C_IMAGE_IS_ACTIVE_NN NOT NULL, 
  LAST_UPD           DATE, 
  CONSTRAINT C_IMAGE_PK
  PRIMARY KEY ( ID ) ) ; 

	
COMMENT ON TABLE C_IMAGE IS 'Contains image descriptions';

COMMENT ON COLUMN C_IMAGE.ID IS 'Unique system number';
COMMENT ON COLUMN C_IMAGE.NAME IS 'Name of the image';
COMMENT ON COLUMN C_IMAGE.DESCRIPTION IS 'Description of the image';
COMMENT ON COLUMN C_IMAGE.FILE_ID IS 'ID of the file related to the image';
COMMENT ON COLUMN C_IMAGE.WIDTH IS 'Visualization width of the image';
COMMENT ON COLUMN C_IMAGE.HEIGHT IS 'Visualization height of the image';
COMMENT ON COLUMN C_IMAGE.IS_ACTIVE IS 'Whether the record is visible or deleted';
COMMENT ON COLUMN C_IMAGE.LAST_UPD IS 'Date of last modification';

CREATE OR REPLACE TRIGGER C_IMAGE_BRIU_TRG BEFORE INSERT OR UPDATE ON C_IMAGE FOR EACH ROW
BEGIN
	:NEW.LAST_UPD := SYSDATE;
END;
/