CREATE TABLE QUESTION ( 
  ID        NUMBER (10)
     CONSTRAINT QUESTION_ID_NN   NOT NULL, 
	QUESTION_TYPE_ID NUMBER(10)
		 CONSTRAINT QUESTION_QUESTION_TYPE_ID_NN NOT NULL,
  DESCRIPTION      CLOB
		 CONSTRAINT QUESTION_DESCRIPTION_NN   NOT NULL, 
  IS_ACTIVE  CHAR (1)      DEFAULT 1
     CONSTRAINT QUESTION_IS_ACTIVE_NN   NOT NULL, 
  LAST_UPD  DATE,
  CONSTRAINT QUESTION_PK
  PRIMARY KEY ( ID ) ) ; 

COMMENT ON TABLE QUESTION IS 'Provides various questions';

COMMENT ON COLUMN QUESTION.ID IS 'Unique system number';
COMMENT ON COLUMN QUESTION.QUESTION_TYPE_ID IS 'ID of the question type';
COMMENT ON COLUMN QUESTION.DESCRIPTION IS 'Description of the question';
COMMENT ON COLUMN QUESTION.IS_ACTIVE IS 'Whether the record is visible or deleted';
COMMENT ON COLUMN QUESTION.LAST_UPD IS 'Date of last modification';


CREATE OR REPLACE TRIGGER QUESTION_BRIU_TRG BEFORE INSERT OR UPDATE ON QUESTION FOR EACH ROW
BEGIN
	:NEW.LAST_UPD := SYSDATE;
END;
/

