CREATE TABLE R_ANSWER_IMAGE ( 
  ID NUMBER (10) CONSTRAINT R_ANSWER_IMAGE_ID_NN NOT NULL, 
  ANSWER_ID NUMBER(10) CONSTRAINT R_ANSWER_IMAGE_ANSWER_ID_NN NOT NULL, 
  IMAGE_ID NUMBER(10) CONSTRAINT R_ANSWER_IMAGE_IMAGE_ID_NN NOT NULL, 
	DESCRIPTION VARCHAR2(256 CHAR),
	IS_ACTIVE CHAR (1) DEFAULT 1 CONSTRAINT R_ANSWER_IMAGE_IS_ACTIVE_NN NOT NULL, 
  LAST_UPD  DATE,
  CONSTRAINT R_ANSWER_IMAGE_PK
  PRIMARY KEY ( ID ) ) ; 

COMMENT ON TABLE R_ANSWER_IMAGE IS 'Provides relations bewteen the answers and the images';

COMMENT ON COLUMN R_ANSWER_IMAGE.ID IS 'Unique system number';
COMMENT ON COLUMN R_ANSWER_IMAGE.ANSWER_ID IS 'ID of the answer';
COMMENT ON COLUMN R_ANSWER_IMAGE.IMAGE_ID IS 'ID of the image';
COMMENT ON COLUMN R_ANSWER_IMAGE.DESCRIPTION IS 'Description of the image';
COMMENT ON COLUMN R_ANSWER_IMAGE.IS_ACTIVE IS 'Whether the record is visible or deleted';
COMMENT ON COLUMN R_ANSWER_IMAGE.LAST_UPD IS 'Date of last modification';


CREATE OR REPLACE TRIGGER ANSWER_BRIU_TRG BEFORE INSERT OR UPDATE ON ANSWER FOR EACH ROW
BEGIN
	:NEW.LAST_UPD := SYSDATE;
END;
/

