CREATE TABLE R_QUESTION_IMAGE ( 
  ID NUMBER (10) CONSTRAINT R_QUESTION_IMAGE_ID_NN NOT NULL, 
  QUESTION_ID NUMBER(10) CONSTRAINT R_QUESTION_IMG_QUESTION_ID_NN NOT NULL, 
  IMAGE_ID NUMBER(10) CONSTRAINT R_QUESTION_IMAGE_IMAGE_ID_NN NOT NULL, 
	DESCRIPTION VARCHAR2(256 CHAR),
	IS_ACTIVE CHAR (1) DEFAULT 1 CONSTRAINT R_QUESTION_IMAGE_IS_ACTIVE_NN NOT NULL, 
  LAST_UPD  DATE,
  CONSTRAINT R_QUESTION_IMAGE_PK
  PRIMARY KEY ( ID ) ) ; 

COMMENT ON TABLE R_QUESTION_IMAGE IS 'Provides relations bewteen the questions and the images';

COMMENT ON COLUMN R_QUESTION_IMAGE.ID IS 'Unique system number';
COMMENT ON COLUMN R_QUESTION_IMAGE.QUESTION_ID IS 'ID of the question';
COMMENT ON COLUMN R_QUESTION_IMAGE.IMAGE_ID IS 'ID of the image';
COMMENT ON COLUMN R_QUESTION_IMAGE.DESCRIPTION IS 'Description of the image';
COMMENT ON COLUMN R_QUESTION_IMAGE.IS_ACTIVE IS 'Whether the record is visible or deleted';
COMMENT ON COLUMN R_QUESTION_IMAGE.LAST_UPD IS 'Date of last modification';


CREATE OR REPLACE TRIGGER QUESTION_BRIU_TRG BEFORE INSERT OR UPDATE ON QUESTION FOR EACH ROW
BEGIN
	:NEW.LAST_UPD := SYSDATE;
END;
/

