CREATE TABLE SYSTEM_PARAMETER ( 
  ID        NUMBER (10)
     CONSTRAINT SYSTEM_PARAMETER_ID_NN   NOT NULL, 
  NAME      VARCHAR2 (256 CHAR)
     CONSTRAINT SYSTEM_PARAMETER_NAME_NN   NOT NULL, 
  VALUE  VARCHAR2(256 CHAR)      
     CONSTRAINT SYSTEM_PARAMETER_VALUE_NN   NOT NULL, 
  LAST_UPD  DATE,
  CONSTRAINT SYSTEM_PARAMETER_PK
  PRIMARY KEY ( ID ) ) ; 

COMMENT ON TABLE SYSTEM_PARAMETER IS 'Provides various system parameter key-value pairs';

COMMENT ON COLUMN SYSTEM_PARAMETER.ID IS 'Unique system number';
COMMENT ON COLUMN SYSTEM_PARAMETER.NAME IS 'Name of the parameter (key)';
COMMENT ON COLUMN SYSTEM_PARAMETER.VALUE IS 'Value of the parameter';
COMMENT ON COLUMN SYSTEM_PARAMETER.LAST_UPD IS 'Date of last modification';


CREATE OR REPLACE TRIGGER SYSTEM_PARAMETER_BRIU_TRG BEFORE INSERT OR UPDATE ON SYSTEM_PARAMETER FOR EACH ROW
BEGIN
	:NEW.LAST_UPD := SYSDATE;
END;
/

